version: '3'
volumes:
  dados:
services:
  email_exercise_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: email_exercise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      #Volume dos Dados
      - dados:/var/b/postgres/data
      #Scripts
      - ./scripts/:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
