version: '3'
volumes:
  dados:
services:
  email_exercise_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: email_exercise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      #Volume dos Dados
      - dados:/var/b/postgres/data
      #Scripts
      - ./scripts/:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: node:10.16.0-slim
    command: bash -c "cd var/app && npm install && npm run serve"
    volumes:
      - ./frontend/:/var/app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
  proxy:
    image: nginx:1.13
    volumes:
      # Configuração do proxy reverso
      - ./nginx/mdefault.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
