version: '3'
volumes:
  dados:
networks:
  banco:
  front:
  back:
  fila:
services:
  email_exercise_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      #Volume dos Dados
      - dados:/var/b/postgres/data
      #Scripts
      - ./scripts/:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    build: frontend
    volumes:
      - ./frontend/:/var/app
    networks:
      - front
  app:
    image: python:3.6
    environment:
      APP_REDIS_HOST: queue
      APP_POSTGRES_HOST: email_exercise_db
      APP_POSTGRES_USER: postgres
      APP_POSTGRES_PASSWORD: password
      APP_DB_NAME: email_sender
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - fila
      - banco
      - back
    depends_on:
      - email_exercise_db
  proxy:
    image: nginx:1.13
    volumes:
      # Configuração do proxy reverso
      - ./nginx/mdefault.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - back
      - front
    depends_on:
      - app
      - frontend
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
